wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1678534115.783841
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.7
      5: 0.13.11
      8:
      - 1
      - 5
d_ff:
  desc: null
  value: 2048
d_model:
  desc: null
  value: 512
dropout:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 3
n_heads:
  desc: null
  value: 8
n_layers:
  desc: null
  value: 2
pos_len:
  desc: null
  value: 200
src_vocab_size:
  desc: null
  value: 4000
tgt_vocab_size:
  desc: null
  value: 4000
